GET http://localhost:4000/api/reviews HTTP/1.1

###
POST http://localhost:4000/api/stores/1/reviews HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwLCJlbWFpbCI6ImFzaGVyX2t1dUBuYXZlci5jb20iLCJpYXQiOjE3MzAxNzEwNjcsImV4cCI6MTczMDc3NTg2N30.r6T_vppxO-HqBcQBP9Aox-eyDRr00vu1X5vsWeV9Qqk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="user_id"

1
--boundary
Content-Disposition: form-data; name="content"

very good
--boundary
Content-Disposition: form-data; name="images"; filename="image.jpg"
Content-Type: image/jpeg

<binary data>
--boundary--

###
PUT http://localhost:4000/api/reviews/1/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwLCJlbWFpbCI6ImFzaGVyX2t1dUBuYXZlci5jb20iLCJpYXQiOjE3MzAxNzEwNjcsImV4cCI6MTczMDc3NTg2N30.r6T_vppxO-HqBcQBP9Aox-eyDRr00vu1X5vsWeV9Qqk
Content-Type: application/json

{
    "user_id": 1,
    "content": "아이가 편안해해요"
}

###
DELETE http://localhost:4000/api/reviews/1/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwLCJlbWFpbCI6ImFzaGVyX2t1dUBuYXZlci5jb20iLCJpYXQiOjE3MzAxNzEwNjcsImV4cCI6MTczMDc3NTg2N30.r6T_vppxO-HqBcQBP9Aox-eyDRr00vu1X5vsWeV9Qqk
Content-Type: application/json

{
    "user_id": 1   
}